[{
    sequenceNum: 1,
    questiomId: 101,
    questionDetails:  "Number of primitive data types in Java are?",
    optionA: "6",
    optionB: "7",
    optionC: "8",
    optionD: "9",
    optionE: "none",
    questionType: "Single Choice",
  },
  {
    sequenceNum: 2,
    questiomId: 102,
    questionDetails: "What is Runnable?",
    optionA: "class",
    optionB: "enum",
    optionC: "interface",
    optionD: "method",
    optionE: "none",
    questionType: "Single Choice",
  },
  {
    sequenceNum: 3,
    questiomId: 103,
    questionDetails: "Which of the following exception is thrown when divided by zero statement is executed?",
    optionA: "NullPointerException",
    optionB: "ClassCastException",
    optionC: "ArithmeticException",
    optionD: "NumberFormatException",
    optionE: "none",
    questionType: "True Or False",
  },
  {
    sequenceNum: 4,
    questiomId: 104,
    questionDetails: "What is the extension of java code files?",
    optionA: ".js",
    optionB: ".txt",
    optionC: ".jsx",
    optionD: ".java",
    optionE: "none",
    questionType: "True Or False",
  },
  {
    sequenceNum: 5,
    questiomId: 105,
    questionDetails: "Which one of the following is not an access modifier?",
    optionA: "pulbic",
    optionB: "protected",
    optionC: "private",
    optionD: "void",
    optionE: "none",
    questionType: "True Or False",
  },
  {
    sequenceNum: 6,
    questiomId: 106,
    questionDetails: " Which function is used to perform some action when the object is to be destroyed?",
    optionA: "finialize()",
    optionB: "delete()",
    optionC: "main()",
    optionD: "remove()",
    optionE: "none",
    questionType: "True Or False",
  },
  {
    sequenceNum: 7,
    questiomId: 107,
    questionDetails: "What is the return type of the hashCode() method in the Object class?",
    optionA: "int",
    optionB: "Integer",
    optionC: "Object",
    optionD: "String",
    optionE: "none",
    questionType: "True Or False",
  },
  {
    sequenceNum: 8,
    questiomId: 108,
    questionDetails: "An interface with no fields or methods is known as a ______.",
    optionA: "Runnable Interface",
    optionB: "Marker Interface",
    optionC: "Abstract  Interface",
    optionD: "CharSequence  Interface",
    optionE: "none",
    questionType: "True Or False",
  },
  {
    sequenceNum: 9,
    questiomId: 109,
    questionDetails: "What is the initial quantity of the ArrayList list?",
    optionA: "5",
    optionB: "10",
    optionC: "20",
    optionD: "15",
    optionE: "none",
    questionType: "True Or False",
  },
  {
    sequenceNum: 10,
    questiomId: 110,
    questionDetails: "JDK stands for ____.",
    optionA: "Java development kit",
    optionB: "Java deployment kit",
    optionC: "JavaScript deployment kit",
    optionD: "JavaScript development kit",
    optionE: "none",
    questionType: "True Or False",
  },]